export type Food = {
  name: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  category: string;
};

export const FOODS_DB: Food[] = [
  // ── Proteína animal ──
  { name: "Pechuga de pollo (cocida)", calories: 165, protein: 31, carbs: 0, fat: 3.6, category: "Proteína" },
  { name: "Muslo de pollo (cocido)", calories: 209, protein: 26, carbs: 0, fat: 11, category: "Proteína" },
  { name: "Pollo entero asado", calories: 239, protein: 27, carbs: 0, fat: 14, category: "Proteína" },
  { name: "Carne de res magra (cocida)", calories: 215, protein: 26, carbs: 0, fat: 12, category: "Proteína" },
  { name: "Carne de res 80/20 (cocida)", calories: 254, protein: 26, carbs: 0, fat: 17, category: "Proteína" },
  { name: "Bife de chorizo", calories: 271, protein: 25, carbs: 0, fat: 19, category: "Proteína" },
  { name: "Asado de tira", calories: 294, protein: 22, carbs: 0, fat: 23, category: "Proteína" },
  { name: "Vacío (cocido)", calories: 250, protein: 27, carbs: 0, fat: 16, category: "Proteína" },
  { name: "Milanesa de res (sin rebozar)", calories: 215, protein: 26, carbs: 0, fat: 12, category: "Proteína" },
  { name: "Milanesa rebozada (frita)", calories: 287, protein: 22, carbs: 12, fat: 17, category: "Proteína" },
  { name: "Milanesa al horno", calories: 230, protein: 24, carbs: 8, fat: 10, category: "Proteína" },
  { name: "Lomo de cerdo", calories: 212, protein: 29, carbs: 0, fat: 10, category: "Proteína" },
  { name: "Costillas de cerdo", calories: 277, protein: 25, carbs: 0, fat: 19, category: "Proteína" },
  { name: "Chorizo parrilla (cocido)", calories: 348, protein: 14, carbs: 2, fat: 31, category: "Proteína" },
  { name: "Morcilla", calories: 297, protein: 12, carbs: 2, fat: 27, category: "Proteína" },
  { name: "Salmón al horno", calories: 208, protein: 20, carbs: 0, fat: 13, category: "Proteína" },
  { name: "Salmón ahumado", calories: 117, protein: 18, carbs: 0, fat: 4.3, category: "Proteína" },
  { name: "Trucha al horno", calories: 190, protein: 27, carbs: 0, fat: 8, category: "Proteína" },
  { name: "Atún en lata (en agua)", calories: 116, protein: 26, carbs: 0, fat: 1, category: "Proteína" },
  { name: "Atún en aceite", calories: 198, protein: 29, carbs: 0, fat: 9, category: "Proteína" },
  { name: "Tilapia al horno", calories: 128, protein: 26, carbs: 0, fat: 2.7, category: "Proteína" },
  { name: "Merluza", calories: 92, protein: 18, carbs: 0, fat: 2, category: "Proteína" },
  { name: "Camarones cocidos", calories: 99, protein: 24, carbs: 0, fat: 0.3, category: "Proteína" },
  { name: "Mejillones cocidos", calories: 172, protein: 24, carbs: 7.4, fat: 4.5, category: "Proteína" },
  { name: "Huevo entero", calories: 155, protein: 13, carbs: 1.1, fat: 11, category: "Proteína" },
  { name: "Clara de huevo", calories: 52, protein: 11, carbs: 0.7, fat: 0.2, category: "Proteína" },
  { name: "Tofu firme", calories: 76, protein: 8, carbs: 1.9, fat: 4.8, category: "Proteína" },
  { name: "Tempeh", calories: 193, protein: 19, carbs: 9, fat: 11, category: "Proteína" },
  { name: "Jamón cocido (bajo grasa)", calories: 107, protein: 17, carbs: 1.5, fat: 3.5, category: "Proteína" },
  { name: "Jamón crudo (serrano)", calories: 250, protein: 28, carbs: 0.5, fat: 15, category: "Proteína" },
  { name: "Pavo pechuga", calories: 135, protein: 30, carbs: 0, fat: 1, category: "Proteína" },
  { name: "Sardinas en lata", calories: 208, protein: 25, carbs: 0, fat: 11, category: "Proteína" },
  { name: "Cordero pierna (cocido)", calories: 258, protein: 26, carbs: 0, fat: 17, category: "Proteína" },

  // ── Lácteos ──
  { name: "Leche entera", calories: 61, protein: 3.2, carbs: 4.8, fat: 3.3, category: "Lácteos" },
  { name: "Leche descremada", calories: 34, protein: 3.4, carbs: 5, fat: 0.1, category: "Lácteos" },
  { name: "Leche chocolatada", calories: 67, protein: 3.4, carbs: 10, fat: 1.5, category: "Lácteos" },
  { name: "Yogur griego (0%)", calories: 59, protein: 10, carbs: 3.6, fat: 0.4, category: "Lácteos" },
  { name: "Yogur natural", calories: 61, protein: 3.5, carbs: 4.7, fat: 3.3, category: "Lácteos" },
  { name: "Yogur saborizado", calories: 95, protein: 3.5, carbs: 17, fat: 1.2, category: "Lácteos" },
  { name: "Queso fresco", calories: 98, protein: 10, carbs: 3.4, fat: 4.3, category: "Lácteos" },
  { name: "Queso mozzarella", calories: 280, protein: 28, carbs: 2.2, fat: 17, category: "Lácteos" },
  { name: "Queso cheddar", calories: 403, protein: 25, carbs: 1.3, fat: 33, category: "Lácteos" },
  { name: "Queso cottage (bajo grasa)", calories: 72, protein: 12, carbs: 2.7, fat: 1, category: "Lácteos" },
  { name: "Queso rallado (parmesano)", calories: 431, protein: 38, carbs: 4, fat: 29, category: "Lácteos" },
  { name: "Queso de bola (gouda)", calories: 356, protein: 25, carbs: 2.2, fat: 28, category: "Lácteos" },
  { name: "Ricota", calories: 174, protein: 11, carbs: 3, fat: 13, category: "Lácteos" },
  { name: "Requesón", calories: 105, protein: 11, carbs: 3, fat: 5, category: "Lácteos" },
  { name: "Crema de leche", calories: 345, protein: 2.8, carbs: 2.8, fat: 36, category: "Lácteos" },

  // ── Carbohidratos ──
  { name: "Arroz blanco cocido", calories: 130, protein: 2.7, carbs: 28, fat: 0.3, category: "Carbohidratos" },
  { name: "Arroz integral cocido", calories: 123, protein: 2.6, carbs: 26, fat: 0.9, category: "Carbohidratos" },
  { name: "Pasta cocida (sin salsa)", calories: 131, protein: 5, carbs: 25, fat: 1.1, category: "Carbohidratos" },
  { name: "Fideos secos (crudo)", calories: 371, protein: 13, carbs: 74, fat: 1.5, category: "Carbohidratos" },
  { name: "Ñoquis de papa cocidos", calories: 130, protein: 3, carbs: 27, fat: 1, category: "Carbohidratos" },
  { name: "Pan blanco", calories: 265, protein: 9, carbs: 49, fat: 3.2, category: "Carbohidratos" },
  { name: "Pan integral", calories: 247, protein: 13, carbs: 41, fat: 4.2, category: "Carbohidratos" },
  { name: "Pan árabe (pita)", calories: 275, protein: 9.1, carbs: 55, fat: 1.2, category: "Carbohidratos" },
  { name: "Tostada de pan (x1 rebanada)", calories: 73, protein: 2.6, carbs: 13, fat: 1, category: "Carbohidratos" },
  { name: "Avena cocida", calories: 71, protein: 2.5, carbs: 12, fat: 1.4, category: "Carbohidratos" },
  { name: "Avena en hojuelas (cruda)", calories: 389, protein: 17, carbs: 66, fat: 7, category: "Carbohidratos" },
  { name: "Granola", calories: 471, protein: 10, carbs: 64, fat: 20, category: "Carbohidratos" },
  { name: "Quinoa cocida", calories: 120, protein: 4.4, carbs: 21, fat: 1.9, category: "Carbohidratos" },
  { name: "Polenta cocida", calories: 70, protein: 1.6, carbs: 15, fat: 0.4, category: "Carbohidratos" },
  { name: "Papa cocida", calories: 87, protein: 1.9, carbs: 20, fat: 0.1, category: "Carbohidratos" },
  { name: "Papa al horno", calories: 93, protein: 2.5, carbs: 21, fat: 0.1, category: "Carbohidratos" },
  { name: "Papa frita (casera)", calories: 312, protein: 3.4, carbs: 41, fat: 15, category: "Carbohidratos" },
  { name: "Batata / Camote cocido", calories: 86, protein: 1.6, carbs: 20, fat: 0.1, category: "Carbohidratos" },
  { name: "Maíz cocido", calories: 96, protein: 3.4, carbs: 21, fat: 1.5, category: "Carbohidratos" },
  { name: "Tortilla de maíz", calories: 218, protein: 5.7, carbs: 44, fat: 3.3, category: "Carbohidratos" },
  { name: "Cuscús cocido", calories: 112, protein: 3.8, carbs: 23, fat: 0.2, category: "Carbohidratos" },
  { name: "Harina de trigo", calories: 364, protein: 10, carbs: 76, fat: 1, category: "Carbohidratos" },

  // ── Legumbres ──
  { name: "Lentejas cocidas", calories: 116, protein: 9, carbs: 20, fat: 0.4, category: "Legumbres" },
  { name: "Garbanzos cocidos", calories: 164, protein: 8.9, carbs: 27, fat: 2.6, category: "Legumbres" },
  { name: "Frijoles negros cocidos", calories: 132, protein: 8.9, carbs: 24, fat: 0.5, category: "Legumbres" },
  { name: "Porotos blancos cocidos", calories: 139, protein: 9.7, carbs: 25, fat: 0.5, category: "Legumbres" },
  { name: "Arvejas cocidas", calories: 84, protein: 5.4, carbs: 15, fat: 0.2, category: "Legumbres" },
  { name: "Edamame cocido", calories: 122, protein: 11, carbs: 10, fat: 5.2, category: "Legumbres" },

  // ── Verduras ──
  { name: "Brócoli al vapor", calories: 35, protein: 2.4, carbs: 7.2, fat: 0.4, category: "Verduras" },
  { name: "Espinacas crudas", calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, category: "Verduras" },
  { name: "Zanahoria cruda", calories: 41, protein: 0.9, carbs: 10, fat: 0.2, category: "Verduras" },
  { name: "Tomate crudo", calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, category: "Verduras" },
  { name: "Lechuga romana", calories: 17, protein: 1.2, carbs: 3.3, fat: 0.3, category: "Verduras" },
  { name: "Pepino crudo", calories: 15, protein: 0.7, carbs: 3.6, fat: 0.1, category: "Verduras" },
  { name: "Cebolla cruda", calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1, category: "Verduras" },
  { name: "Pimiento rojo", calories: 31, protein: 1, carbs: 6, fat: 0.3, category: "Verduras" },
  { name: "Pimiento verde", calories: 20, protein: 0.9, carbs: 4.6, fat: 0.2, category: "Verduras" },
  { name: "Coliflor al vapor", calories: 25, protein: 1.9, carbs: 5, fat: 0.3, category: "Verduras" },
  { name: "Calabacín crudo", calories: 17, protein: 1.2, carbs: 3.1, fat: 0.3, category: "Verduras" },
  { name: "Berenjena cocida", calories: 35, protein: 0.8, carbs: 8.7, fat: 0.2, category: "Verduras" },
  { name: "Col rizada (kale)", calories: 49, protein: 4.3, carbs: 9, fat: 0.9, category: "Verduras" },
  { name: "Apio crudo", calories: 16, protein: 0.7, carbs: 3, fat: 0.2, category: "Verduras" },
  { name: "Champiñones crudos", calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3, category: "Verduras" },
  { name: "Espárragos cocidos", calories: 22, protein: 2.4, carbs: 4.1, fat: 0.2, category: "Verduras" },
  { name: "Remolacha cocida", calories: 44, protein: 1.7, carbs: 10, fat: 0.2, category: "Verduras" },
  { name: "Chauchas cocidas", calories: 35, protein: 1.9, carbs: 7.9, fat: 0.1, category: "Verduras" },
  { name: "Repollo crudo", calories: 25, protein: 1.3, carbs: 5.8, fat: 0.1, category: "Verduras" },
  { name: "Acelga cocida", calories: 20, protein: 1.9, carbs: 3.7, fat: 0.1, category: "Verduras" },
  { name: "Zapallo cocido", calories: 26, protein: 1, carbs: 6.5, fat: 0.1, category: "Verduras" },
  { name: "Choclo desgranado cocido", calories: 96, protein: 3.4, carbs: 21, fat: 1.5, category: "Verduras" },
  { name: "Puerro cocido", calories: 31, protein: 0.8, carbs: 7.6, fat: 0.2, category: "Verduras" },
  { name: "Ajo crudo", calories: 149, protein: 6.4, carbs: 33, fat: 0.5, category: "Verduras" },

  // ── Frutas ──
  { name: "Manzana", calories: 52, protein: 0.3, carbs: 14, fat: 0.2, category: "Frutas" },
  { name: "Plátano / Banana", calories: 89, protein: 1.1, carbs: 23, fat: 0.3, category: "Frutas" },
  { name: "Naranja", calories: 47, protein: 0.9, carbs: 12, fat: 0.1, category: "Frutas" },
  { name: "Fresa / Frutilla", calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3, category: "Frutas" },
  { name: "Uvas", calories: 69, protein: 0.7, carbs: 18, fat: 0.2, category: "Frutas" },
  { name: "Sandía", calories: 30, protein: 0.6, carbs: 7.6, fat: 0.2, category: "Frutas" },
  { name: "Melón", calories: 34, protein: 0.8, carbs: 8.2, fat: 0.2, category: "Frutas" },
  { name: "Pera", calories: 57, protein: 0.4, carbs: 15, fat: 0.1, category: "Frutas" },
  { name: "Durazno / Melocotón", calories: 39, protein: 0.9, carbs: 10, fat: 0.3, category: "Frutas" },
  { name: "Mango", calories: 60, protein: 0.8, carbs: 15, fat: 0.4, category: "Frutas" },
  { name: "Piña / Ananá", calories: 50, protein: 0.5, carbs: 13, fat: 0.1, category: "Frutas" },
  { name: "Kiwi", calories: 61, protein: 1.1, carbs: 15, fat: 0.5, category: "Frutas" },
  { name: "Mandarina", calories: 53, protein: 0.8, carbs: 13, fat: 0.3, category: "Frutas" },
  { name: "Arándanos", calories: 57, protein: 0.7, carbs: 14, fat: 0.3, category: "Frutas" },
  { name: "Ciruela", calories: 46, protein: 0.7, carbs: 11, fat: 0.3, category: "Frutas" },
  { name: "Cereza", calories: 63, protein: 1.1, carbs: 16, fat: 0.2, category: "Frutas" },
  { name: "Granada", calories: 83, protein: 1.7, carbs: 19, fat: 1.2, category: "Frutas" },
  { name: "Lima", calories: 30, protein: 0.7, carbs: 11, fat: 0.2, category: "Frutas" },
  { name: "Limón", calories: 29, protein: 1.1, carbs: 9.3, fat: 0.3, category: "Frutas" },
  { name: "Maracuyá", calories: 97, protein: 2.2, carbs: 23, fat: 0.7, category: "Frutas" },
  { name: "Papaya", calories: 43, protein: 0.5, carbs: 11, fat: 0.3, category: "Frutas" },
  { name: "Higo", calories: 74, protein: 0.8, carbs: 19, fat: 0.3, category: "Frutas" },

  // ── Grasas ──
  { name: "Aguacate / Palta", calories: 160, protein: 2, carbs: 9, fat: 15, category: "Grasas" },
  { name: "Aceite de oliva", calories: 884, protein: 0, carbs: 0, fat: 100, category: "Grasas" },
  { name: "Aceite de girasol", calories: 884, protein: 0, carbs: 0, fat: 100, category: "Grasas" },
  { name: "Mantequilla / Manteca", calories: 717, protein: 0.9, carbs: 0.1, fat: 81, category: "Grasas" },
  { name: "Almendras", calories: 579, protein: 21, carbs: 22, fat: 50, category: "Grasas" },
  { name: "Nueces", calories: 654, protein: 15, carbs: 14, fat: 65, category: "Grasas" },
  { name: "Maníes / Cacahuates", calories: 567, protein: 26, carbs: 16, fat: 49, category: "Grasas" },
  { name: "Mantequilla de maní", calories: 588, protein: 25, carbs: 20, fat: 50, category: "Grasas" },
  { name: "Semillas de chía", calories: 486, protein: 17, carbs: 42, fat: 31, category: "Grasas" },
  { name: "Semillas de lino", calories: 534, protein: 18, carbs: 29, fat: 42, category: "Grasas" },
  { name: "Semillas de calabaza", calories: 559, protein: 30, carbs: 11, fat: 49, category: "Grasas" },
  { name: "Maíz pochoclo (sin manteca)", calories: 387, protein: 13, carbs: 78, fat: 5, category: "Grasas" },
  { name: "Aceitunas verdes", calories: 145, protein: 1, carbs: 3.8, fat: 15, category: "Grasas" },
  { name: "Tahini (pasta de sésamo)", calories: 595, protein: 17, carbs: 21, fat: 54, category: "Grasas" },

  // ── Comidas argentinas ──
  { name: "Empanada de carne (horneada)", calories: 285, protein: 12, carbs: 28, fat: 14, category: "Comidas AR" },
  { name: "Empanada de pollo", calories: 245, protein: 13, carbs: 26, fat: 10, category: "Comidas AR" },
  { name: "Empanada de queso y cebolla", calories: 270, protein: 9, carbs: 28, fat: 14, category: "Comidas AR" },
  { name: "Asado mixto (res + chorizo)", calories: 310, protein: 23, carbs: 1, fat: 24, category: "Comidas AR" },
  { name: "Locro (porción)", calories: 210, protein: 12, carbs: 24, fat: 8, category: "Comidas AR" },
  { name: "Guiso de lentejas", calories: 145, protein: 8, carbs: 20, fat: 4, category: "Comidas AR" },
  { name: "Carbonada", calories: 165, protein: 10, carbs: 18, fat: 6, category: "Comidas AR" },
  { name: "Puchero (porción)", calories: 180, protein: 15, carbs: 14, fat: 7, category: "Comidas AR" },
  { name: "Suprema de pollo", calories: 260, protein: 22, carbs: 10, fat: 14, category: "Comidas AR" },
  { name: "Fideos con tuco casero", calories: 155, protein: 7, carbs: 24, fat: 4, category: "Comidas AR" },
  { name: "Tarta de verdura (porción)", calories: 220, protein: 7, carbs: 22, fat: 12, category: "Comidas AR" },
  { name: "Pizza de mozzarella (porción)", calories: 266, protein: 11, carbs: 33, fat: 10, category: "Comidas AR" },
  { name: "Medialunas (c/u)", calories: 150, protein: 3.5, carbs: 21, fat: 6, category: "Comidas AR" },
  { name: "Facturas (c/u)", calories: 180, protein: 4, carbs: 25, fat: 8, category: "Comidas AR" },
  { name: "Alfajor de maicena (c/u)", calories: 145, protein: 2, carbs: 25, fat: 5, category: "Comidas AR" },
  { name: "Alfajor de chocolate (c/u)", calories: 265, protein: 4, carbs: 37, fat: 12, category: "Comidas AR" },

  // ── Comidas internacionales ──
  { name: "Arroz con pollo (casero)", calories: 170, protein: 12, carbs: 22, fat: 4, category: "Comidas" },
  { name: "Hamburguesa (sin pan)", calories: 295, protein: 24, carbs: 0, fat: 21, category: "Comidas" },
  { name: "Hamburguesa completa", calories: 520, protein: 30, carbs: 38, fat: 26, category: "Comidas" },
  { name: "Ensalada César (sin aderezo)", calories: 34, protein: 2.8, carbs: 5.5, fat: 0.7, category: "Comidas" },
  { name: "Ensalada de atún", calories: 130, protein: 18, carbs: 4, fat: 5, category: "Comidas" },
  { name: "Wrap de pollo", calories: 210, protein: 18, carbs: 22, fat: 6, category: "Comidas" },
  { name: "Sopa de verdura casera", calories: 50, protein: 2, carbs: 9, fat: 0.8, category: "Comidas" },
  { name: "Sushi (nigiri x1 pieza)", calories: 50, protein: 3, carbs: 8, fat: 0.5, category: "Comidas" },
  { name: "Tacos de carne (x1)", calories: 210, protein: 14, carbs: 20, fat: 8, category: "Comidas" },
  { name: "Bowl de quinoa y vegetales", calories: 200, protein: 8, carbs: 30, fat: 6, category: "Comidas" },
  { name: "Revuelto de huevos (2 huevos)", calories: 200, protein: 14, carbs: 1.5, fat: 15, category: "Comidas" },

  // ── Bebidas ──
  { name: "Agua", calories: 0, protein: 0, carbs: 0, fat: 0, category: "Bebidas" },
  { name: "Café negro", calories: 2, protein: 0.3, carbs: 0, fat: 0, category: "Bebidas" },
  { name: "Café con leche entera", calories: 34, protein: 1.8, carbs: 2.5, fat: 1.7, category: "Bebidas" },
  { name: "Mate (sin azúcar)", calories: 5, protein: 0.3, carbs: 0.5, fat: 0, category: "Bebidas" },
  { name: "Té sin azúcar", calories: 2, protein: 0, carbs: 0.5, fat: 0, category: "Bebidas" },
  { name: "Jugo de naranja natural", calories: 45, protein: 0.7, carbs: 10, fat: 0.2, category: "Bebidas" },
  { name: "Leche de almendra sin azúcar", calories: 13, protein: 0.5, carbs: 0.3, fat: 1.1, category: "Bebidas" },
  { name: "Leche de avena", calories: 45, protein: 1, carbs: 7.5, fat: 1.5, category: "Bebidas" },
  { name: "Coca-Cola (lata 330ml)", calories: 139, protein: 0, carbs: 35, fat: 0, category: "Bebidas" },
  { name: "Coca-Cola Zero (lata 330ml)", calories: 1, protein: 0, carbs: 0.3, fat: 0, category: "Bebidas" },
  { name: "Jugo de fruta (200ml)", calories: 88, protein: 0.4, carbs: 22, fat: 0.2, category: "Bebidas" },
  { name: "Batido de proteína (agua)", calories: 120, protein: 25, carbs: 3, fat: 2, category: "Bebidas" },
  { name: "Leche chocolatada (200ml)", calories: 140, protein: 5, carbs: 22, fat: 3.5, category: "Bebidas" },
  { name: "Chocolatada Toddynho (200ml)", calories: 138, protein: 4.8, carbs: 22, fat: 3.2, category: "Bebidas" },
  { name: "Chocolatada baja en grasa (200ml)", calories: 110, protein: 5.5, carbs: 18, fat: 1.8, category: "Bebidas" },
  { name: "Jugo de manzana (200ml)", calories: 90, protein: 0.1, carbs: 22, fat: 0.2, category: "Bebidas" },
  { name: "Cerveza (330ml)", calories: 143, protein: 1, carbs: 13, fat: 0, category: "Bebidas" },
  { name: "Vino tinto (150ml)", calories: 125, protein: 0.1, carbs: 3.8, fat: 0, category: "Bebidas" },
  { name: "Agua con gas (500ml)", calories: 0, protein: 0, carbs: 0, fat: 0, category: "Bebidas" },
  { name: "Gatorade (500ml)", calories: 130, protein: 0, carbs: 34, fat: 0, category: "Bebidas" },

  // ── Dulces y golosinas ──
  { name: "Helado de crema (100g)", calories: 207, protein: 3.5, carbs: 23, fat: 11, category: "Dulces" },
  { name: "Helado de agua / palito (100g)", calories: 75, protein: 0.5, carbs: 18, fat: 0.2, category: "Dulces" },
  { name: "Helado de vainilla (1 bocha)", calories: 137, protein: 2.3, carbs: 15, fat: 7, category: "Dulces" },
  { name: "Helado de chocolate (1 bocha)", calories: 145, protein: 2.5, carbs: 16, fat: 8, category: "Dulces" },
  { name: "Helado de frutilla (1 bocha)", calories: 110, protein: 1.5, carbs: 17, fat: 4, category: "Dulces" },
  { name: "Helado de dulce de leche (1 bocha)", calories: 155, protein: 2.8, carbs: 19, fat: 7.5, category: "Dulces" },
  { name: "Helado de limón (1 bocha)", calories: 95, protein: 0.5, carbs: 22, fat: 1.2, category: "Dulces" },
  { name: "Chocolate con leche (30g)", calories: 160, protein: 2.2, carbs: 17, fat: 9, category: "Dulces" },
  { name: "Chocolate negro 70% (30g)", calories: 170, protein: 2.5, carbs: 13, fat: 12, category: "Dulces" },
  { name: "Alfajor simple (c/u)", calories: 230, protein: 3, carbs: 35, fat: 9, category: "Dulces" },
  { name: "Alfajor triple (c/u)", calories: 380, protein: 5, carbs: 55, fat: 15, category: "Dulces" },
  { name: "Facturas (medialuna, c/u)", calories: 230, protein: 4.5, carbs: 30, fat: 10, category: "Dulces" },
  { name: "Facturas (vigilante, c/u)", calories: 210, protein: 4, carbs: 28, fat: 9, category: "Dulces" },
  { name: "Galletitas dulces (30g)", calories: 138, protein: 1.8, carbs: 21, fat: 5, category: "Dulces" },
  { name: "Galletitas de arroz (30g)", calories: 115, protein: 2.2, carbs: 24, fat: 1, category: "Dulces" },
  { name: "Budin de limón (porción 100g)", calories: 340, protein: 5, carbs: 50, fat: 13, category: "Dulces" },
  { name: "Brownie (porción 80g)", calories: 340, protein: 4, carbs: 45, fat: 17, category: "Dulces" },
  { name: "Torta de chocolate (porción 100g)", calories: 380, protein: 5, carbs: 52, fat: 18, category: "Dulces" },
  { name: "Gelatina light (100g)", calories: 15, protein: 1.5, carbs: 2.5, fat: 0, category: "Dulces" },
  { name: "Mermelada (1 cucharada)", calories: 50, protein: 0.1, carbs: 13, fat: 0, category: "Dulces" },
  { name: "Dulce de leche (1 cucharada)", calories: 65, protein: 1.2, carbs: 12, fat: 1.5, category: "Dulces" },
  { name: "Miel (1 cucharada)", calories: 64, protein: 0.1, carbs: 17, fat: 0, category: "Dulces" },

  // ── Suplementos ──
  { name: "Proteína whey (1 scoop)", calories: 120, protein: 25, carbs: 3, fat: 2, category: "Suplementos" },
  { name: "Proteína caseína (1 scoop)", calories: 110, protein: 24, carbs: 3, fat: 1, category: "Suplementos" },
  { name: "Creatina (1 cucharadita)", calories: 0, protein: 0, carbs: 0, fat: 0, category: "Suplementos" },
  { name: "Proteína en polvo (whey, 100g)", calories: 373, protein: 78, carbs: 8, fat: 5, category: "Suplementos" },
  { name: "Barrita de proteína (c/u)", calories: 200, protein: 20, carbs: 22, fat: 7, category: "Suplementos" },
  { name: "Avena proteica (100g)", calories: 360, protein: 22, carbs: 52, fat: 6, category: "Suplementos" },
];

export function searchFoods(query: string, customFoods: Food[] = []): Food[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  const all = [...FOODS_DB, ...customFoods];
  return all.filter((f) => f.name.toLowerCase().includes(q)).slice(0, 15);
}
